run:
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - goimports
    - revive
    - govet
    - staticcheck
    - stylecheck

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0